INSERT INTO "Dat" VALUES
        ('Apl_AdmPas',  'CONTRASEÑA DEL ADMINISTRADOR EN md5',  'c', '835e50d9c38018637b2cca8215183555', '', '', '', '(Admin1967)MODIFIQUELA PARA PONER LA SUYA', 'PARA MODIFCACIONES SIN CONTROL DE USUARIOS (en md5)', '{Usr}',   '{DateTime}'),
        ('Apl_Apl',     'NUEVO NOMBRE DE LA APLICACION',        'c', '{«Apl_Apl»}',                           '', '', '', 'MODIFIQUELO o QUIETELO',                    '',                                                    '{Usr}',   '{DateTime}'),
        ('Apl_Nom',     'NUEVO TITULO DEL MENU',                'c', 'NOMBRE APLICACION EN TABLA Dat',   '', '', '', 'MODIFIQUELO o QUIETELO',                    '',                                                    '{Usr}',   '{DateTime}'),
        ('Eml_Svr',     'SERVIDOR',                             'c', '',                                 '', '', '', '',                                          '',                                                    '{Usr}',   '{DateTime}'),
        ('Eml_Puo',     'PUERTO',                               'c', '',                                 '', '', '', '',                                          '',                                                    '{Usr}',   '{DateTime}'),
        ('Eml_Usr',     'USUARIO',                              'c', '',                                 '', '', '', '',                                          '',                                                    '{Usr}',   '{DateTime}'),
        ('Eml_Pas',     'CONTRASEÑA',                           'c', '',                                 '', '', '', '',                                          '',                                                    '{Usr}',   '{DateTime}'),
        ('Eml_EmlEnv',  'EMAIL DE ENVIO',                       'c', '',                                 '', '', '', '',                                          '',                                                    '{Usr}',   '{DateTime}'),
        ('Eml_EmlDst',  'EMAIL DESTINATARIO DE LA APLICACION',  'c', '',                                 '', '', '', '',                                          '',                                                    '{Usr}',   '{DateTime}'),
        ('Eml_MsgCab',  'CABECERA DEL MENSAJE',                 'c', '',                                 '', '', '', '',                                          '',                                                    '{Usr}',   '{DateTime}'),
        ('Eml_MsgPie',  'PIE DEL MENSAJE',                      'c', '',                                 '', '', '', '',                                          '',                                                    '{Usr}',   '{DateTime}');
