INSERT INTO 'ClmMod' VALUES
    ('Bdt',    'Main', '010', 'cSvr',    'SERVIDOR',          'Mod', 'N', '',                      '',                                                '{Usr}', '{DateTime}'),
    ('Bdt',    'Main', '020', 'cSvrTip', 'TIPO',              'Mod', 'N', '',                      '',                                                '{Usr}', '{DateTime}'),
    ('Bdt',    'Main', '030', 'cDir',    'DIRECCION',         'Mod', 'N', '',                      '',                                                '{Usr}', '{DateTime}'),
    ('Bdt',    'Main', '040', 'cUsr',    'USUARIO',           'Mod', '',  '',                      '',                                                '{Usr}', '{DateTime}'),
    ('Bdt',    'Main', '050', 'cPas',    'CONTRASEÑA',        'Mod', '',  '',                      '',                                                '{Usr}', '{DateTime}'),
    ('Bdt',    'Main', '060', 'cBdt',    'BASE DE DATOS',     'Mod', '',  '',                      '',                                                '{Usr}', '{DateTime}'),
    ('Bdt',    'Main', '070', 'cObs',    'OBSERVACIONES',     'Mod', '',  '',                      '',                                                '{Usr}', '{DateTime}'),

    ('Dat',    'Main', '020', 'cNom',    'VARIABLE',          'Mod', 'N', '',                      '',                                                '{Usr}', '{DateTime}'),
    ('Dat',    'Main', '030', 'cDes',    'DESCRIPCION',       'Mod', 'N', '',                      '',                                                '{Usr}', '{DateTime}'),
    ('Dat',    'Main', '040', 'cTipClm', 'TIPO COLUMNA',      'Mod', 'N', 'c,d,m,l',               '',                                                '{Usr}', '{DateTime}'),
    ('Dat',    'Main', '050', 'cVal',    'VALOR',             'Mod', 'N', '',                      '',                                                '{Usr}', '{DateTime}'),
    ('Dat',    'Main', '060', 'cValPmd', 'VALOR INICIAL',     'Mod', '',  '',                      '',                                                '{Usr}', '{DateTime}'),
    ('Dat',    'Main', '070', 'cLonClm', 'LONGITUD',          'Mod', '',  '',                      '',                                                '{Usr}', '{DateTime}'),
    ('Dat',    'Main', '080', 'cAli',    'ALINEACION',        'Mod', '',  ',C,D',                  'Blanco  o I-Izquierda, C-Centro, D-Derecha',      '{Usr}', '{DateTime}'),
    ('Dat',    'Main', '090', 'cObs',    'OBSERVACIONES',     'Mod', '',  '',                      '',                                                '{Usr}', '{DateTime}'),
    ('Dat',    'Main', '100', 'cObsSis', 'OBSERVACIONES SIS', 'Cre', '',  '',                      '',                                                '{Usr}', '{DateTime}'),

    ('Mnu',    'Main', '010', 'cMnu',    'MENU',              'Mod', 'N', '',                      '',                                                '{Usr}', '{DateTime}'),
    ('Mnu',    'Main', '020', 'cNum',    'Nº ORDEN',          'Mod', 'N', '',                      '',                                                '{Usr}', '{DateTime}'),
    ('Mnu',    'Main', '030', 'cTip',    'TIPO',              'Mod', '',  'Cab,Opc',               '',                                                '{Usr}', '{DateTime}'),
    ('Mnu',    'Main', '040', 'cEtn',    'ENTORNO',           'Mod', '',  ',Windows,Linux,Darwin', ',Vacio=Todos, Windows, Linux, Darwin (macOS)',    '{Usr}', '{DateTime}'),
    ('Mnu',    'Main', '050', 'cTxt',    'TEXTO',             'Mod', 'N', '',                      '',                                                '{Usr}', '{DateTime}'),
    ('Mnu',    'Main', '060', 'cFnc',    'FUNCION',           'Mod', '',  '',                      '',                                                '{Usr}', '{DateTime}'),
    ('Mnu',    'Main', '070', 'cObs',    'OBSERVACIONES',     'Mod', '',  '',                      '',                                                '{Usr}', '{DateTime}'),

    ('Ord',    'Main', '010', 'cTab',    'TABLA',             'Mod', 'N', '',                      '',                                                '{Usr}', '{DateTime}'),
    ('Ord',    'Main', '020', 'cNum',    'Nº ORDEN',          'Mod', 'N', '',                      '',                                                '{Usr}', '{DateTime}'),
    ('Ord',    'Main', '050', 'cTxt',    'TEXTO',             'Mod', 'N', '',                      '',                                                '{Usr}', '{DateTime}'),
    ('Ord',    'Main', '050', 'cCmd',    'COMANDO',           'Mod', 'N', '',                      '',                                                '{Usr}', '{DateTime}'),
    ('Ord',    'Main', '060', 'cObs',    'OBSERVACIONES',     'Mod', '',  '',                      '',                                                '{Usr}', '{DateTime}'),

    ('Brw',    'Main', '010', 'cTab',    'TABLA',             'Mod', 'N', '',                      '',                                                '{Usr}', '{DateTime}'),
    ('Brw',    'Main', '020', 'cCod',    'CODIGO',            'Mod', 'N', '',                      '',                                                '{Usr}', '{DateTime}'),
    ('Brw',    'Main', '030', 'cNum',    'Nº ORDEN',          'Mod', 'N', '',                      '',                                                '{Usr}', '{DateTime}'),
    ('Brw',    'Main', '040', 'cCab',    'CABECERA',          'Mod', 'N', '',                      '',                                                '{Usr}', '{DateTime}'),
    ('Brw',    'Main', '050', 'cLon',    'LONGITUD',          'Mod', 'N', '',                      '',                                                '{Usr}', '{DateTime}'),
    ('Brw',    'Main', '060', 'cClm',    'COLUMNA',           'Mod', 'N', '',                      '',                                                '{Usr}', '{DateTime}'),
    ('Brw',    'Main', '070', 'cObs',    'OBSERVACIONES',     'Mod', '',  '',                      '',                                                '{Usr}', '{DateTime}'),

    ('ClmMod', 'Main', '010', 'cTab',    'TABLA',             'Mod', 'N', '',                      '',                                                '{Usr}', '{DateTime}'),
    ('ClmMod', 'Main', '020', 'cCod',    'CODIGO',            'Mod', 'N', '',                      '',                                                '{Usr}', '{DateTime}'),
    ('ClmMod', 'Main', '030', 'cNum',    'Nº ORDEN',          'Mod', 'N', '',                      '',                                                '{Usr}', '{DateTime}'),
    ('ClmMod', 'Main', '040', 'cClm',    'COLUMNA',           'Mod', 'N', '',                      '',                                                '{Usr}', '{DateTime}'),
    ('ClmMod', 'Main', '050', 'cCab',    'CABECERA',          'Mod', 'N', '',                      '',                                                '{Usr}', '{DateTime}'),
    ('ClmMod', 'Main', '060', 'cMod',    'MODIFICAR',         'Mod', '',  'Mod,Cre,',              'Cre=Creacion ,Mod=Cre y Modificar =Solo Lectura', '{Usr}', '{DateTime}'),
    ('ClmMod', 'Main', '070', 'cNul',    'NULO',              'Mod', '',  ',N',                    'N=NO Nulo',                                       '{Usr}', '{DateTime}'),
    ('ClmMod', 'Main', '080', 'cOpc',    'OPCIONES',          'Mod', '',  '',                      '',                                                '{Usr}', '{DateTime}'),
    ('ClmMod', 'Main', '090', 'cObs',    'OBSERVACIONES',     'Mod', '',  '',                      '',                                                '{Usr}', '{DateTime}');