INSERT INTO 'Ord' VALUES
	('Bdt',    '010', 'SERVIDOR',              'cSvr',                 '', '{Usr}', '{DateTime}'),
        ('Bdt',    '020', 'TIPO',                  'cSvrTip',              '', '{Usr}', '{DateTime}'),
        ('Bdt',    '030', 'MODIFICADO',            'cModRegTim',           '', '{Usr}', '{DateTime}'),
	('Dat',    '010', 'VARIABLE',              'cNom',                 '', '{Usr}', '{DateTime}'),
        ('Dat',    '020', 'MODIFICADO',            'cModRegTim',           '', '{Usr}', '{DateTime}'),
        ('Mnu',    '010', 'MENU + ORDEN',          'cMnu || cNum',         '', '{Usr}', '{DateTime}'),
        ('Mnu',    '020', 'TEXTO',                 'cTxt',                 '', '{Usr}', '{DateTime}'),
        ('Mnu',    '030', 'MODIFICADO',            'cModRegTim',           '', '{Usr}', '{DateTime}'),
        ('Ord',    '010', 'TABLA + ORDEN',         'cTab || cNum',         '', '{Usr}', '{DateTime}'),
        ('Ord',    '020', 'MODIFICADO',            'cModRegTim',           '', '{Usr}', '{DateTime}'),
        ('Brw',    '010', 'TABLA + BRWSE + ORDEN', 'cTab || cCod || cNum', '', '{Usr}', '{DateTime}'),
        ('Brw',    '020', 'MODIFICADO',            'cModRegTim',           '', '{Usr}', '{DateTime}'),
        ('ClmMod', '010', 'TABLA + ORDEN',         'cTab || cNum',         '', '{Usr}', '{DateTime}'),
        ('ClmMod', '020', 'MODIFICADO',            'cModRegTim',           '', '{Usr}', '{DateTime}');